### PR TITLE
WDIO test stability

### PR DESCRIPTION
**Pull request by AronNovak**
Now it seems it's very rare that WDIO passes, so let's try to solve it ASAP, at local repeatedly the tests are okay, so it's almost certainly timing and/or resource-usage related.

#60

### CODE REVIEW

**Comment by AronNovak** [comment]
There are actually two things to do to record sane videos:
 * significantly lower the resolution to make the compression less resource heavy, done in https://github.com/Gizra/drupal-elm-starter/pull/68/commits/7c437cef995bd5e61868786fbabec5cea57a0b5f
 * do not try to spot the start of the browser simply by watching VLC, ffmpeg can do scene detection: http://stackoverflow.com/a/38205105 - then it's possible to start the playback from the given position

So now, again trying to record the failure on Travis with these improved conditions.

**Comment by AronNovak** [comment]
https://drive.google.com/file/d/0B7FpNcQYpf7GQjFJU2VlUkRIcHc/view?usp=sharing
A captured failed execution at Travis, 25FPS, 1024x768.

**Comment by amitaibu** [comment]
cool!

**Comment by AronNovak** [comment]
When we fail at Travis, the browser contains this:
error

**Comment by amitaibu** [comment]
>  ffmpeg can do scene detection

Worth checking if the scene detection is already in the chrome docker. Otherwise, worth suggesting it there. @elgalu is doing some pretty awesome stuff with that repo 😄

**Comment by AronNovak** [comment]
Yep, thanks, they responded with a very valuable suggestion, that there is https://github.com/zalando/zalenium what supports this out of the box.

What I'd do here as next steps to resolve the issue:
* after WDIO test failure, list Apache error log/access log (make sure we don't discard it)
* after WDIO test failure, list Watchdog messages via Drush

Then we'd have a better understanding why the network error can happen.

**Comment by AronNovak** [comment]
The latest failure has very exciting job log:
bad-cred

Drush says that WDIO tries to connect with bad credentials two times. actually it should happen only once. My idea could be that https://github.com/Gizra/drupal-elm-starter/blob/master/client/test/specs/login.js#L9 is not effective yet (always) when we hit the submit button. @amitaibu do you think it's somehow possible? Did you experience such timing issues while working with WDIO tests?
As a next step, i'd add a simple wait before both `browser.submitForm('.login-form');`s to see if it'd make the test robust.

**Comment by amitaibu** [comment]
@rohanorton can you please assist @AronNovak with the WDIO tests

**Comment by amitaibu** [comment]
@rohanorton we can probably copy/ paste `setValueSafe` and use it here instead

**Comment by AronNovak** [comment]
Awesome, thanks @rohanorton ! It seems the instability is now solved!
Now I am going to revert all the simplifications (like no client test, etc) and soon it won't be WIP anymore.

@amitaibu Do you think I should invest more in a solid video-exposing at this PR (or at a follow-up)? It's a realistic goal, the upload part is missing, the recording works fine (without scene manipulation however).

**Comment by amitaibu** [comment]
I think the video upload can be a follow up for a later time

**Comment by amitaibu** [comment]
@AronNovak ready for review?

**Comment by AronNovak** [comment]
Yep!

**Comment by amitaibu** [comment]
Awesome, thanks guys!

**Pull request merged**
