### PR TITLE
WIP: Headless Chrome

### LINKED ISSUE #160: Utilize Headless Chrome for WDIO [3h]
Instead of loading a heavy Docker container, let's consider Headless Chrome for executing WDIO tests.

Possibly even video recording can be preserved:
 - https://github.com/ChromeDevTools/devtools-protocol/issues/17#issuecomment-302782170

### PR DESCRIPTION
**Pull request by AronNovak**
will fix #160 

## Status
dropped Zalenium image

## Todo
make headless chrome working

### CODE REVIEW

**Comment by AronNovak** [comment]
I try out if the Google Chrome static binary can be used within our Docker Container, trying to configure WDIO accrding to: https://stackoverflow.com/questions/42303119/selenium-webdriverio-chrome-headless

**(0.45/3h)**

**Comment by AronNovak** [comment]
based on my local attempt, let WDIO connect to Headless Chrome. But just as at local, i expect the tests to fail, to be debugged why.
(0.95/3h)

**Comment by AronNovak** [comment]
**3/3h**

As I spent time debugging this, the https://github.com/Gizra/drupal-lamp is in our way.
It's quite an old Debian 8, it has old Java version, it has old NPM version.
We can workaround everything, but as I easily reached the timebox here, it's clear that it's not efficient.

There are to major ways:
1. Keep maintaining our own Docker image, we can create a more modern one, and so on
2. Relying on Travis to maintain the base Docker image, with the evolution of Travis, now if we don't require sudo (which we don't really need), we can still have the ability of local testing: https://medium.com/google-developers/how-to-run-travisci-locally-on-docker-822fc6b2db2e

I would go with the 2nd option, but it would extend the scope significantly, not just headless Chrome, but to throw away https://github.com/Gizra/drupal-lamp, and configure everything at the Docker environment what Travis uses.

**Comment by amitaibu** [comment]
I also think the 2nd option is more appealing. The main reason for docker was being able to debug so if indeed https://medium.com/google-developers/how-to-run-travisci-locally-on-docker-822fc6b2db2e as easily possible, then it sounds like the way to go.

**Comment by AronNovak** [comment]
closing in favor of https://github.com/Gizra/drupal-elm-starter/pull/162

**Pull request closed without merging**
