### PR TITLE
CI - More aggressive caching for Drupal and NPM

### LINKED ISSUE #103: Speedup builds by caching data [8h]
We could benefit from [caching](https://docs.travis-ci.com/user/caching/#Enabling-multiple-caching-features) `node_modules`, and Drupal's contrib modules.

The way I imagine this is we hold a checksum of `package.json` and of `drupal.make` -- so if it changes we'll know to invalidate the cache.

This will probably mean that in our docker we should be able to mount the content of `node_modules` and `www/profiles/../modules|themes` from Travis.

@AronNovak 6h sounds ok to you?

### PR DESCRIPTION
**Pull request by AronNovak**
## Status

Started to think about the structure

## Todo:
 - cache Drupal source (except custom modules)
 - cache NPM installs
 - add invalidation logic
 - tests

will fix #103

### CODE REVIEW

**Comment by AronNovak** [comment]
I spent 5.25 hours on this issue so far, i still have a little remaining, but likely i will run out of time here. The only thing left however is to debug. At local, using Docker Compose, I could trigger the cache use, and it worked, on Travis, it fails, it says some modules are missing, so somehow the content of the cache is unusable. Apart from this, what was planned was implemented, for both Drupal and NPM.

**Comment by AronNovak** [comment]
```  mkdir -p "$TRAVIS_CACHE_DIR"/www_ignored
  for FILE in $(git ls-files --others -i --exclude-standard)
  do  
    cp --parents "$FILE" "$TRAVIS_CACHE_DIR"/www_ignored
  done
```

Tested at local Docker execution, this part is not yet effective, debugging to be continued.
`ci-scripts/docker_files/post_cache.sh`

**Comment by AronNovak** [comment]
The caching itself works, i cannot tell the exact numbers, but i expected a bit better improvement of execution speed.
I wanted to invite our @gizra-robot friend to post a video, as many things were changed, but waiting for https://github.com/zalando/zalenium/issues/131 to be able to continue.

**Comment by AronNovak** [comment]
Ready for review. The speed gain will be likely even more for real-world projects based on Elm Starter, where the `drush si` is slower for instance.

**Comment by AronNovak** [comment]
may1

**Comment by amitaibu** [comment]
Lovely!

**Pull request merged**
