### PR TITLE
Error handling and Translate

### PR DESCRIPTION
**Pull request by amitaibu**
#97

### CODE REVIEW

**Comment by amitaibu** [comment]
**0.5/3h**: I've decided to add also the Translation here, so maybe timebox will need some bumping. But currently app is compiling, so next is wiring all to the error handler.

**Comment by amitaibu** [comment]
**0.75/3h**: Added also `debug` property to `Config`.

**Comment by amitaibu** [comment]
elm

**Comment by amitaibu** [comment]
**1.5/3h**: I'm now moving all `text "..` to use `translateText`

One thing I've done here, is divide the translations strings by topic/module -- so it's easier to cleanup unused strings.

**Comment by amitaibu** [comment]
**2/3h**: All non-debug related text is now under `Trans`.

**Comment by amitaibu** [comment]
2.5/3h: Added unit tests for the `Error` module.

**Comment by amitaibu** [comment]
@AronNovak once this will be green, I'll assign to you to complete the Travis part of WDIO that looks for the debug-errors

**Comment by amitaibu** [comment]
@bitamar notice that way I've structured `Translate.elm` -- I think it makes it easier to maintain.

**Comment by bitamar** [comment]
@amitaibu  - It seems indeed better to have small lists of translations per region. I just wonder what happens when you need the same phrase in two different places, would you duplicate the translation?

**Comment by amitaibu** [comment]
> happens when you need the same phrase in two different places, would you duplicate the translatio

No, maybe I'd move it to another place. Not sure -- I guess we will need to find a use case.

**Comment by amitaibu** [comment]
Travis is green, @AronNovak can you please add the Travis part.

**Comment by AronNovak** [comment]
**2.75/3h**

started to adapt the solution from another project

**Comment by AronNovak** [comment]
**2.9/3h**

Tried to trigger test failure via the new code.

**Comment by AronNovak** [comment]
the Travis part is settled now

**Pull request merged**
