### PR TITLE
Adding docker to travis

### PR DESCRIPTION
**Pull request by ordavidil**
#1

### CODE REVIEW

**Comment by amitaibu** [comment]
Thanks. When ready, if you can also update the Travis build icon on the README, and merge

**Comment by ordavidil** [comment]
@amitaibu 
any suggestions about this one before I dig in ?
job__3_2_-_gizra_drupal-elm-starter_-_travis_ci

**Comment by amitaibu** [comment]
Yeah, I completely forgot about the Client tests :/

**Comment by ordavidil** [comment]
@amitaibu 
I've disabled the client build for now (via the `.travis.yml` file)
anytime that we wish we just need to change the variable back to `1`.

ready for review.

**Comment by amitaibu** [comment]
It's fun how quick it's now to set it up!

**Comment by ordavidil** [comment]
especially when things works just out of the box like that   :)
gizra_drupal-elm-starter__a_starter_kit_for_headless_drupal_with_elm

**Comment by amitaibu** [comment]
amazing! worth a post :)

**Pull request merged**
