### PR TITLE
Adds a XSS item to the migrated items

### LINKED ISSUE #69: Add XSS items to migrate [1h]
To confirm our client side is escaping it properly

### PR DESCRIPTION
**Pull request by DavidHernandez**
Will fix #69 
xss
xss2

### CODE REVIEW

**Comment by amitaibu** [comment]
Seems we have a client failure, that @AronNovak knows how to deal with :)

**Comment by AronNovak** [comment]
I have a way to do that, but it's not yet working, I'll follow-up when it's the case.

**Comment by AronNovak** [comment]
After https://github.com/Gizra/drupal-elm-starter/pull/74 is green, I will merge it to master and master can be merged to 69-migrate-xss-items, then it has the chance to be green.

**Comment by AronNovak** [comment]
It's fully green now, Travis is not in the best shape today, it produced some non-client related unstable failures....

**Comment by amitaibu** [comment]
Thanks guys

**Pull request merged**
